name: bancos_brasileiros
description: A JSON list of brazilian commercial banks.
version: 1.0.0
repository: https://github.com/guibranco/BancosBrasileiros

environment:
  sdk: ^3.1.3

assets:
  - bancos.json

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
